export const GET_USERS = 'GET_USERS';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const SAVE_QUESTION= 'SAVE_QUESTION';
export const SAVE_ANSWER= 'SAVE_ANSWER';
export const SET_LOADING= 'SET_LOADING';
export const GET_AUTHED_USER= 'GET_AUTHER_USER';
export const LOGOUT_AUTHEDUSER= 'LOGOUT_AUTHEDUSER';
